#!/usr/bin/env bash
# Packages a self-contained PortalSDK.xcframework for Swift consumers.
#
# The KMP cinterop klibs embed their matching Go archives, so the assembled
# framework is already self-contained. This script verifies the engine symbols,
# copies the XCFramework, zips it deterministically, and emits a SwiftPM
# manifest that carries Security framework linkage.
#
# Prerequisites (macOS only):
#   ./gradlew :portal-sdk:assemblePortalSDKReleaseXCFramework
#
# Output:
#   dist/PortalSDK.xcframework      self-contained distribution
#   dist/PortalSDK.xcframework.zip  release asset for the SwiftPM binary target
#   dist/Package.swift              manifest with the computed checksum
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DIST="$ROOT/dist"
XCF_SRC="$ROOT/portal-sdk/build/XCFrameworks/release/PortalSDK.xcframework"

for tool in lipo ditto swift; do
    command -v "$tool" >/dev/null || { echo "error: $tool not found (macOS required)" >&2; exit 1; }
done
[ -d "$XCF_SRC" ] || { echo "error: $XCF_SRC missing — run assemblePortalSDKReleaseXCFramework" >&2; exit 1; }

rm -rf "$DIST/PortalSDK.xcframework"
mkdir -p "$DIST"
cp -R "$XCF_SRC" "$DIST/PortalSDK.xcframework"

echo "==> verifying embedded engine symbols"
framework_count=0
while IFS= read -r bin; do
    for sym in PortalStart PortalStop PortalFreeString; do
        # grep -q would exit on the first match and SIGPIPE nm (exit 141)
        # under pipefail on large archives; consume the full listing instead.
        nm -g "$bin" 2>/dev/null | grep -E " _?${sym}$" >/dev/null || {
            echo "error: $sym missing from $bin" >&2; exit 1;
        }
    done
    lipo -info "$bin"
    framework_count=$((framework_count + 1))
done < <(find "$DIST/PortalSDK.xcframework" -type f -path '*/PortalSDK.framework/PortalSDK')
[ "$framework_count" -ge 2 ] || {
    echo "error: expected device and simulator PortalSDK framework binaries" >&2
    exit 1
}
echo "==> zipping for SwiftPM binary distribution"
rm -f "$DIST/PortalSDK.xcframework.zip"
ditto -c -k --sequesterRsrc --keepParent \
    "$DIST/PortalSDK.xcframework" "$DIST/PortalSDK.xcframework.zip"

CHECKSUM="$(swift package compute-checksum "$DIST/PortalSDK.xcframework.zip")"
echo "==> swiftpm checksum: $CHECKSUM"

cat > "$DIST/Package.swift" <<EOF
// swift-tools-version:5.7
// Generated by scripts/package-ios-xcframework.sh — do not edit by hand.
import PackageDescription

let package = Package(
    name: "PortalSDK",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "PortalSDK", targets: ["PortalSDKLink"])
    ],
    targets: [
        // The binary target keeps the framework's module name so consumers
        // write \`import PortalSDK\`. The thin wrapper target exists only to
        // carry the Security framework linkage a binary target cannot declare.
        .binaryTarget(
            name: "PortalSDK",
            url: "https://github.com/gosuda/portal-multiplatform-sdk/releases/download/RELEASE_TAG/PortalSDK.xcframework.zip",
            checksum: "$CHECKSUM"
        ),
        .target(
            name: "PortalSDKLink",
            dependencies: ["PortalSDK"],
            linkerSettings: [.linkedFramework("Security")]
        )
    ]
)
EOF

echo "==> done"
echo "    $DIST/PortalSDK.xcframework"
echo "    $DIST/PortalSDK.xcframework.zip"
echo "    $DIST/Package.swift (replace RELEASE_TAG before publishing)"
